language: node_js
node_js:
- "7"
addons:
- firefox: "latest"
cache:
  directories:
  - node_modules
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run test_single_run
- npm run buildHeroku
deploy:
  provider: surge
  project: ./dist/
  domain: wet-snake.surge.sh